# Generated by Django 5.1 on 2024-08-27 20:08

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "username",
                    models.CharField(
                        help_text="Укажите логин пользователя",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="Логин",
                    ),
                ),
                ("password", models.CharField(help_text="Укажите пароль", max_length=128, verbose_name="Пароль")),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите электронную почту", max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Укажите телефон для связи", max_length=15, verbose_name="Телефон"),
                ),
                ("birth_date", models.DateField(help_text="Укажите дату рождения", verbose_name="Дата рождения")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата редактирования")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Пользователь"), ("admin", "Администратор")],
                        default="user",
                        help_text="Укажите роль пользователя",
                        max_length=5,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Укажите активен ли пользователь", verbose_name="Активация"
                    ),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ["username"],
            },
        ),
    ]
